name: instagram_clone
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  simple_animations: ^4.0.1
  flutter_svg: ^1.0.3
  intl_phone_number_input: ^0.7.0+2
  geolocator: ^8.0.3
  geocoding: ^2.0.2
  image_picker: ^0.8.4+11
  font_awesome_flutter: ^9.2.0
  firebase_core: ^1.13.1
  firebase_auth: ^3.3.11
  firebase_storage: ^10.2.9
  cloud_firestore: ^3.1.10
  shared_preferences: ^2.0.13
  fluttertoast: ^8.0.9
  cached_network_image: ^3.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/content_img/
    - assets/images/profile_page_img/
    - assets/images/user_img/

  fonts:
    - family: Billabong
      fonts:
        - asset: assets/fonts/Billabong.ttf


